# Generated by Django 5.2.5 on 2025-12-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_sessions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="token_key",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
